@startuml
actor user as U
participant Telegram as T
participant "RAG Application" as R
database "Vector Database" as VDB
database "Document Storage" as DS
participant VLM as M
U -> T : Ask questions
T -> R : Webhook
R -> VDB : Retreive Context
VDB --> R
R -> DS : Retrieve Documents
DS --> R: Documents
R -> M: Prompt + context + documents
M --> R: Response (JSON)
R --> T: Response (text)
T --> U: Response 
@enduml