@startuml

left to right direction

actor "Foreign Employee" as Employee
actor "Admin" as Admin

rectangle "RAG System" {

    usecase "Ask question" as UC_Ask
    usecase "View cited documents" as UC_Cited
    usecase "Give feedback" as UC_Feedback

    usecase "View history" as UC_History
    usecase "Login" as UC_Login
    usecase "Manage feedbacks" as UC_ManageFeedback
    usecase "Manage documents" as UC_ManageDocuments

    UC_Cited ..> UC_Ask : <<extend>>
    UC_Feedback ..> UC_Ask : <<extend>>
}

Employee --> UC_Ask
Employee --> UC_History

Admin --> UC_Login
Admin --> UC_ManageFeedback
Admin --> UC_ManageDocuments

@enduml